version: '3'
services:
  filini:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=filini
    networks:
      - filini_network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: filini
    ports:
      - "5432:5432"
    networks:
      - filini_network

networks:
  filini_network:
    driver: bridge
