version: '3'
services:
  filini:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - filini_network
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - filini_network
    env_file:
      - .env

networks:
  filini_network:
    driver: bridge
